module.exports = {
    parserOption: {
        ecmaVersion: 2017,
        sourceType: "module",
        ecmaFeatures: {
            impliedStrict: true,
            experimentalObjectRestSpread: true
        }
    },
    env: {
        browser: true,
        es6: true
    },
    rules: {
        // Possible errors (http://eslint.org/docs/rules/#possible-errors)
        "no-await-in-loop": "warn",
        "no-cond-assign": "error",
        "no-console": "warn",
        "no-constant-condition": "error",
        "no-control-regex": "warn",
        "no-debugger": "warn",
        "no-dupe-args": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty-character-class": "warn",
        "no-empty": "warn",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "warn",
        "no-extra-semi": "warn",
        "no-func-assign": "error",
        "no-inner-declarations": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "warn",
        "no-obj-calls": "error",
        "no-regex-spaces": "warn",
        "no-sparse-arrays": "error",
        "no-template-curly-in-string": "error",
        "no-unexpected-multiline": "error",
        "no-unreachable": "warn",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "warn",
        "use-isnan": "error",
        "valid-typeof": ["error", { requireStringLiterals: true }],

        // Best practices (http://eslint.org/docs/rules/#best-practices)
        "curly": ["warn", "all"],
        "default-case": "error",
        "dot-notation": "warn",
        "eqeqeq": ["warn", "smart"],
        "no-alert": "warn",
        "no-caller": "error",
        "no-case-declarations": "error",
        "no-else-return": "warn",
        "no-empty-function": "error",
        "no-empty-pattern": "error",
        "no-eq-null": "error",
        "no-eval": "error",
        "no-extend-native": "error",
        "no-extra-bind": "warn",
        "no-fallthrough": "error",
        "no-floating-decimal": "warn",
        "no-global-assign": "error",
        "no-implicit-coercion": "warn",
        "no-implicit-globals": "error",
        "no-implied-eval": "error",
        "no-invalid-this": "error",
        "no-iterator": "error",
        "no-lone-blocks": "error",
        "no-loop-func": "error",
        "no-magic-numbers": "warn",
        "no-multi-spaces": "warn",
        "no-new-func": "error",
        "no-new-wrappers": "error",
        "no-new": "error",
        "no-octal": "error",
        "no-param-reassign": "error",
        "no-proto": "error",
        "no-redeclare": ["error", { builtinGlobals: true }],
        "no-return-assign": ["warn", "always"],
        "no-return-await": "warn",
        "no-script-url": "error",
        "no-self-assign": "error",
        "no-self-compare": "error",
        "no-sequences": "error",
        "no-throw-literal": "error",
        "no-unmodified-loop-condition": "error",
        "no-unused-labels": "warn",
        "no-useless-call": "warn",
        "no-useless-concat": "warn",
        "no-useless-escape": "warn",
        "no-useless-return": "warn",
        "radix": "error",
        "require-await": "warn",
        "wrap-iife": "error",

        // Variables (http://eslint.org/docs/rules/#variables)
        "no-delete-var": "error",
        "no-shadow-restricted-names": "error",
        "no-undef": "error",
        "no-undefined": "error",
        "no-use-before-define": "error",

        // Stylistic Issues (http://eslint.org/docs/rules/#stylistic-issues)
        "array-bracket-spacing": "warn",
        "block-spacing": "warn",
        "brace-style": ["warn", "stroustrup", { allowSingleLine: true }],
        "camelcase": "warn",
        "comma-dangle": ["warn", "always-multiline"],
        "comma-spacing": "warn",
        "comma-style": "warn",
        "computed-property-spacing": "warn",
        "eol-last": "warn",
        "func-call-spacing": "warn",
        "func-name-matching": ["warn", "always"],
        "func-names": ["warn", "as-needed"],
        "indent": ["warn", 4],
        "key-spacing": "warn",
        "keyword-spacing": "warn",
        "max-depth": ["warn", 4],
        "new-cap": "warn",
        "new-parens": "warn",
        "newline-before-return": "warn",
        "newline-per-chained-call": "warn",
        "no-array-constructor": "warn",
        "no-bitwise": "warn",
        "no-lonely-if": "warn",
        "no-mixed-spaces-and-tabs": ["warn", "smart-tabs"],
        "no-multiple-empty-lines": "warn",
        "no-negated-condition": "warn",
        "no-nested-ternary": "warn",
        "no-new-object": "warn",
        "no-trailing-spaces": "warn",
        "no-underscore-dangle": "warn",
        "no-unneeded-ternary": "warn",
        "no-whitespace-before-property": "warn",
        "object-curly-newline": ["warn", { minProperties: 2 }],
        "object-curly-spacing": ["warn", "always"],
        "object-property-newline": "warn",
        "one-var-declaration-per-line": "warn",
        "quote-props": ["warn", "as-needed", { keywords: true }],
        "quotes": ["warn", "double", {
            avoidEscape: true,
            allowTemplateLiterals: true
        }],
        "semi-spacing": "warn",
        "semi": "warn",
        "space-before-blocks": "warn",
        // "space-before-function-paren": ["warn", {
        //     anonymous: true,
        //     named: false
        // }],
        "space-in-parens": "warn",
        "space-infix-ops": "warn",
        "space-unary-ops": ["warn", {
            words: true,
            nonwords: false
        }],

        // ECMAScript 6 (http://eslint.org/docs/rules/#ecmascript-6)
        "arrow-body-style": "warn",
        "arrow-parens": ["warn", "as-needed", { requireForBlockBody: true }],
        "arrow-spacing": "warn",
        "constructor-super": "warn",
        "no-class-assign": "warn",
        "no-const-assign": "error",
        "no-dupe-class-members": "warn",
        "no-duplicate-imports": "warn",
        "no-new-symbol": "error",
        "no-this-before-super": "error",
        "no-useless-computed-key": "warn",
        "no-useless-constructor": "warn",
        "no-useless-rename": "warn",
        "no-var": "warn",
        "object-shorthand": "warn",
        "prefer-arrow-callback": "warn",
        "prefer-const": "warn",
        "prefer-destructuring": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
        "prefer-template": "warn",
        "rest-spread-spacing": "warn",
        "symbol-description": "warn",
        "template-curly-spacing": "warn"
    }
}
